import type { NextPage } from 'next'
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center text-center p-3 lg:text-left lg:flex-row lg:mx-32 lg:justify-between lg:mt-28">
        <div className="flex flex-col gap-y-8 lg:gap-y-16 lg:w-1/2">
          <h1 className="text-6xl lg:text-8xl font-black">
            Discover how <br /> you{" "}
            <span className="text-cr-green">listen.</span>
          </h1>
          <p className="text-xl lg:text-3xl font-light">
            Explore your music taste, profile <br /> and create awesome
            playlists
          </p>
          <button className="flex justify-center items-center py-5 gap-x-5 lg:gap-x-2 bg-cr-light-green lg:w-2/5 rounded-md">
            <Image
              src="/icons/Spotify.png"
              height={30}
              width={30}
              alt="icon: cruunchify logo"
            />
            <small className="text-lg capitalize">Continue with spotify</small>
          </button>
        </div>
        <div className="hidden lg:block w-1/2">
          <div className="w-[400px] h-[500px] bg-[url('/images/lea-paci-landing.png')] bg-no-repeat bg-cover border-5 rounded-lg relative p-5">
            <Image
              src="/icons/Spotify.png"
              height={40}
              width={40}
              alt="icon: spotify logo"
            />
            <div className="absolute bottom-5">
              <h3 className="text-5xl font-bold pb-5">Léa Paci</h3>
              {/* Genres and Actions */}
              <div className="flex gap-x-20">
                {/* Genres */}
                <div className="flex gap-5">
                  <div className="px-5 py-3 bg-cr-genre rounded-3xl capitalize">
                    french pop
                  </div>
                  <div className="px-5 py-3 bg-white text-black flex justify-center items-center rounded-3xl">
                    +2
                  </div>
                </div>
                {/* Play Btn */}
                <Image
                  src="/icons/Play.png"
                  height={50}
                  width={50}
                  alt="icon: play on spotify"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home
