import type { NextPage } from 'next'
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex mx-32 justify-between mt-28">
        <div className="flex flex-col gap-y-16 w-1/2">
          <h1 className="text-9xl font-black">
            Discover how <br /> you{" "}
            <span className="text-cr-green">listen.</span>
          </h1>
          <p className="text-3xl font-light">
            Explore your music taste, profile <br /> and create awesome
            playlists
          </p>
          <button className="flex justify-center items-center gap-x-2 bg-cr-light-green w-2/5 py-6 rounded-md">
            <Image
              src="/icons/Spotify.png"
              height={30}
              width={30}
              alt="icon: cruunchify logo"
            />
            <small className="text-xl capitalize">Continue with spotify</small>
          </button>
        </div>
        <div className="text-blue-200 w-1/2">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusamus,
          exercitationem.
        </div>
      </main>
    </div>
  );
};

export default Home
